use_frameworks!

source 'https://github.com/YeebZ/testPod.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyPodTest_Example' do
  pod 'MyPodTest', :path => '../'

  target 'MyPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
